Repository bigcommerce/checkout-js, pull requests merged in 2021-12, with the labels that each got.

#722 feat(payment): INT-4897 Humm - Show Humm as payment method
  src/app/payment/Payment.tsx
  src/app/payment/paymentMethod/PaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethodId.ts
  src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Labels: integrations, sydney, reviewed, ready to merge

#762 refactor(payment): INT-1866 Update Visa Checkout to Visa SRC
  src/app/locale/translations/de.json
  src/app/locale/translations/en.json
  src/app/locale/translations/fr.json
  src/app/locale/translations/it.json
  src/app/locale/translations/nl.json
  src/app/locale/translations/pt-BR.json
  src/app/locale/translations/pt.json
  src/app/locale/translations/sv.json
  src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Labels: integrations, sydney, reviewed, ready to merge

#748 feat(payment): INT-5000 DigitalRiver: populate onUnhandledError correctly
  src/app/locale/translations/en.json
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge, important

#738 test(payment): INT-4855 increase code coverage on CheckoutcomCustomFo…
  src/app/payment/paymentMethod/CheckoutcomCustomFormFields.spec.tsx
  src/app/payment/paymentMethod/CheckoutcomCustomFormFields.tsx
Labels: integrations, reviewed, ready to merge

#773 feat(payment): INT-4893 Add translations for errors from SDK - Humm
  src/app/locale/translations/en.json
  src/app/payment/mapSubmitOrderErrorMessage.spec.ts
  src/app/payment/mapSubmitOrderErrorMessage.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#757 fix(payment): INT-5153 Mollie: added card code validation
  src/app/payment/paymentMethod/MolliePaymentMethod.spec.tsx
  src/app/payment/paymentMethod/MolliePaymentMethod.tsx
Labels: integrations, reviewed, ready to merge
