Repository bigcommerce/checkout-js, pull requests merged in 2021-09, with the labels that each got.

#686 feat(payment): INT-4809 Remove compliance section in Drop-in
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge

#690 feat(payment): BOLT-24 added Bolt account creation checkbox into Bolt EmbeddedPaymentMethod component
  package-lock.json
  package.json
  src/app/locale/translations/en.json
  src/app/payment/PaymentForm.spec.tsx
  src/app/payment/PaymentForm.tsx
  src/app/payment/paymentMethod/BoltCustomForm.spec.tsx
  src/app/payment/paymentMethod/BoltCustomForm.tsx
  src/app/payment/paymentMethod/BoltEmbeddedPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/BoltEmbeddedPaymentMethod.tsx
  src/scss/components/bigcommerce/forms-ccFields/_forms-ccFields.scss
Labels: reviewable, sydney

#693 feat(payment): INT-4828 Adding custom error message for all dropin error
  src/app/locale/translations/en.json
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge, important

#696 fix(checkout): CHECKOUT-5980 invalid aria-labelledby values
  src/app/address/getAddressFormFieldInputId.ts
  src/app/address/googleAutocomplete/GoogleAutocompleteFormField.tsx
  src/app/ui/autocomplete/Autocomplete.tsx
Labels: reviewable

#700 fix(checkout): CHECKOUT-5928 Shopper cannot switch back to use single shipping address in checkout
  src/app/shipping/Shipping.spec.tsx
  src/app/shipping/Shipping.tsx
Labels: reviewable

#692 feat(payment): INT-4631 Add Openpay payment method
  src/app/locale/translations/en.json
  src/app/payment/Payment.tsx
  src/app/payment/PaymentSubmitButton.spec.tsx
  src/app/payment/PaymentSubmitButton.tsx
  src/app/payment/paymentMethod/PaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethodId.ts
  src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Labels: integrations, sydney, reviewed, ready to merge, important

#637 feat(payment): INT-4170 Stripe: use hosted fields for verification fields for stored instruments
  src/app/payment/paymentMethod/StripePaymentMethod.spec.tsx
  src/app/payment/paymentMethod/StripePaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge

#711 feat(payment): INT-4836 Openpay: New logo on checkout page
  src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Labels: integrations, sydney, reviewed, ready to merge
