Repository bigcommerce/checkout-js, pull requests merged in 2021-04, with the labels that each got.

#547 fix(payment): INT-4100 added ability to translate SEPA display name
  src/app/locale/translations/en.json
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Labels: integrations, ready to merge, reviewed, sydney

#528 feat(payments): INT-2503 Fawry custom form
  src/app/locale/translations/en.json
  src/app/payment/PaymentForm.tsx
  src/app/payment/checkoutcomFieldsets/getCheckoutcomFieldsetValidationSchemas.tsx
  src/app/payment/checkoutcomFieldsets/index.ts
  src/app/payment/paymentMethod/CheckoutcomCustomFormFields.tsx
  src/app/payment/paymentMethod/CreditCardPaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethodId.ts
Labels: integrations, ready to merge, reviewed, sydney

#541 feat(payment): INT-4021 Checkout.com iDeal add BIC field as a dropdown
  src/app/locale/translations/en.json
  src/app/payment/PaymentForm.tsx
  src/app/payment/checkoutcomFieldsets/getCheckoutcomFieldsetValidationSchemas.spec.ts
  src/app/payment/checkoutcomFieldsets/getCheckoutcomFieldsetValidationSchemas.tsx
  src/app/payment/checkoutcomFieldsets/index.ts
  src/app/payment/paymentMethod/CheckoutcomCustomFormFields.spec.tsx
  src/app/payment/paymentMethod/CheckoutcomCustomFormFields.tsx
  src/app/payment/paymentMethod/CreditCardPaymentMethod.tsx
Labels: important, integrations, ready to merge, reviewed, sydney

#552 fix(checkout): INT-4180 Display method name along with the icon for checkout.com
  src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Labels: important, integrations, ready to merge, reviewed, sydney

#491 feat(payment): INT-3702 Added vaulted credit card support for Mollie
  src/app/payment/paymentMethod/HostedWidgetPaymentMethod.tsx
  src/app/payment/paymentMethod/MollieCustomCardForm.tsx
  src/app/payment/paymentMethod/MolliePaymentMethod.spec.tsx
  src/app/payment/paymentMethod/MolliePaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
  src/scss/components/bigcommerce/forms-ccFields/_forms-ccFields.scss
Labels: important, integrations, ready to merge, reviewed, sydney

#558 fix(checkout): INT-4229 Fix checkout.com logo for credit card on phase 1
  src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Labels: important, ready to merge, reviewed, sydney

#560 feat(payment): INT-4150 adding zip to handlebeforeunload function
  src/app/payment/Payment.tsx
Labels: integrations, ready to merge, reviewed, sydney
