Repository bigcommerce/checkout-js, pull requests merged in 2021-08, with the labels that each got.

#663 fix(payment): INT-4709 Display "place order button" when payment is not required
  src/app/payment/paymentMethod/HostedDropInPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/HostedDropInPaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge, important

#652 feat(payments): INT-4686 removing disabledPaymentMethods for digitalriver
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge, important

#672 chore(payment): INT-4672 bump checkout-sdk
  package-lock.json
  package.json
Labels: integrations, reviewable, sydney

#651 fix(payment): INT-3946 using supported locales on masterpass SRC
  src/app/locale/index.ts
  src/app/locale/masterpassFormatLocale.spec.ts
  src/app/locale/masterpassFormatLocale.ts
  src/app/payment/paymentMethod/MasterpassPaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge

#676 feat(payment): INT-4660 button text update on Checkout for Klarna
  src/app/locale/translations/en.json
  src/app/payment/PaymentSubmitButton.tsx
Labels: integrations, reviewed, ready to merge

#680 chore(checkout): CHECK-5757 bump up checkout-sdk
  package-lock.json
  package.json
Labels: reviewed, dependencies, ready to merge
