Repository bigcommerce/checkout-js, pull requests merged in 2021-05, with the labels that each got.

#562 feat(payment): INT-4193 Add ticket url for OXXO/Boleto on checkout.com
  src/app/locale/translations/en.json
  src/app/order/OrderStatus.tsx
Labels: important, integrations, ready to merge, reviewed, sydney

#571 feat(payment): INT-4184 Add Creditor and Debtor to Sepa
  src/app/locale/translations/en.json
  src/app/payment/checkoutcomFieldsets/getCheckoutcomFieldsetValidationSchemas.spec.ts
  src/app/payment/checkoutcomFieldsets/getCheckoutcomFieldsetValidationSchemas.tsx
  src/app/payment/paymentMethod/CheckoutcomCustomFormFields.spec.tsx
  src/app/payment/paymentMethod/CheckoutcomCustomFormFields.tsx
  src/app/payment/paymentMethod/CheckoutcomCustomPaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethod.spec.tsx
  src/scss/components/checkout/paymentProvider/_paymentProvider.scss
Labels: important, ready to merge, reviewed, sydney

#567 fix(payment): INT-4287 Fix Fawry payment
  src/app/payment/PaymentForm.tsx
  src/app/payment/checkoutcomFieldsets/getCheckoutcomFieldsetValidationSchemas.tsx
  src/app/payment/paymentMethod/CheckoutcomCustomFormFields.tsx
Labels: integrations, ready to merge, reviewed, sydney

#565 feat(payment): INT-4071 Clearpay - Create payment method
  src/app/payment/Payment.tsx
  src/app/payment/paymentMethod/PaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethodId.ts
  src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
  src/app/payment/paymentMethod/getPaymentMethodName.spec.ts
  src/app/payment/paymentMethod/getPaymentMethodName.ts
Labels: integrations, qa pending, ready to merge, reviewed, sydney

#549 feat(payment): PAYPAL-976 Order placement v2
  package-lock.json
  package.json
  src/app/payment/paymentMethod/PaymentMethod.tsx
  src/app/payment/paymentMethod/PaypalCommercePaymentMethod.tsx
Labels: sydney

#587 fix(payment): INT-4184 Add missing payment type to SEPA
  src/app/locale/translations/en.json
  src/app/payment/paymentMethod/CheckoutcomCustomFormFields.tsx
  src/scss/components/checkout/paymentProvider/_paymentProvider.scss
Labels: integrations, ready to merge, reviewed, sydney

#566 feat(payment): INT-4237 Add issuer for Mollie APMs
  src/app/payment/paymentMethod/MollieAPMCustomForm.spec.tsx
  src/app/payment/paymentMethod/MollieAPMCustomForm.tsx
  src/app/payment/paymentMethod/MollieCustomCardForm.spec.tsx
  src/app/payment/paymentMethod/MollieCustomCardForm.tsx
  src/app/payment/paymentMethod/MolliePaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
  src/scss/components/checkout/instrumentSelect/_instrumentSelect.scss
Labels: important, integrations, ready to merge, reviewed, sydney

#593 feat(payment): INT-4289 Suppress payment methods out of scope on Digital River
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
Labels: integrations, reviewed, sydney

#584 feat(checkout): INT-4151 Create custom Place Order button for Bolt
  src/app/locale/translations/en.json
  src/app/payment/PaymentSubmitButton.spec.tsx
  src/app/payment/PaymentSubmitButton.tsx
  src/app/ui/icon/IconBolt.tsx
  src/app/ui/icon/index.ts
  src/scss/components/checkout/paymentProvider/_paymentProvider.scss
Labels: integrations, ready to merge, reviewed, sydney

#600 test(payment): INT-0000 Increase branch coverage threshold for BlueSn…
  src/app/payment/paymentMethod/BlueSnapV2PaymentMethod.spec.tsx
Labels: integrations, reviewable, sydney

#591 feat(payment): INT-4310 Create HostedDropInPaymentMethod
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
  src/app/payment/paymentMethod/HostedDropInPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/HostedDropInPaymentMethod.tsx
Labels: integrations, ready to merge, reviewed, sydney
