Repository bigcommerce/checkout-js, pull requests merged in 2021-06, with the labels that each got.

#572 feat(payment): INT-4242 Add Quadpay payment method
  src/app/locale/translations/en.json
  src/app/payment/Payment.tsx
  src/app/payment/PaymentSubmitButton.spec.tsx
  src/app/payment/PaymentSubmitButton.tsx
  src/app/payment/paymentMethod/PaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethodId.ts
  src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Labels: important, integrations, ready to merge, reviewed

#563 feat(payment): INT-4205 Create Moneris payment Method
  src/app/payment/paymentMethod/MonerisPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/MonerisPaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethodId.ts
Labels: integrations, ready to merge, reviewed, sydney

#611 feat(payment): INT-4170 added hosted_field schema for Mollie
  src/app/payment/paymentMethod/HostedWidgetPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/HostedWidgetPaymentMethod.tsx
  src/app/payment/paymentMethod/MolliePaymentMethod.tsx
Labels: important, integrations, ready to merge, reviewed, sydney

#608 feat(payment): INT-3792 Disabled payment method due to settings
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
Labels: integrations, ready to merge, reviewed, sydney

#613 feat(payment): INT-4441 Update Mollie APMs logos
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Labels: integrations, ready to merge, reviewed, sydney
