Repository bigcommerce/checkout-js, pull requests merged in 2021-07, with the labels that each got.

#612 feat(payment): INT-4342 added Google Pay for Orbital
  src/app/customer/CheckoutButtonList.tsx
  src/app/payment/paymentMethod/GooglePayPaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethodId.ts
Labels: integrations, ready to merge, reviewed, sydney

#622 feat(payments): INT-4237 Added select your bank to json
  src/app/locale/translations/en.json
  src/app/payment/paymentMethod/MollieAPMCustomForm.spec.tsx
  src/app/payment/paymentMethod/MollieAPMCustomForm.tsx
Labels: integrations, ready to merge, reviewed, sydney

#602 fix(customer): Disable continue as guest button when loading
  src/app/customer/CheckoutButtonList.spec.tsx
  src/app/customer/CheckoutButtonList.tsx
  src/app/customer/Customer.tsx
  src/app/customer/GuestForm.spec.tsx
  src/app/customer/GuestForm.tsx
Labels: integrations, ready to merge, reviewed, sydney

#615 feat(payment): INT-4222 Vaulting for Moneris
  src/app/payment/paymentMethod/MonerisPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/MonerisPaymentMethod.tsx
Labels: important, integrations, ready to merge, reviewed, sydney

#648 feat(payment): PAYPAL-1090 bump checkout-sdk-js version
  package-lock.json
  package.json
Labels: sydney

#641 feat(payment): PAYPAL-1057 added check of showOnlyOnMobileDevices APM…
  jest-setup.ts
  package-lock.json
  package.json
  src/app/common/utility/index.ts
  src/app/common/utility/isMobile.spec.ts
  src/app/common/utility/isMobile.ts
  src/app/payment/payment-methods.mock.ts
  src/app/payment/paymentMethod/PaymentMethodList.spec.tsx
  src/app/payment/paymentMethod/PaymentMethodList.tsx
Labels: sydney

#642 feat(payment): INT-4605 Zip: Display special text for PaymentSubmitButton
  src/app/payment/PaymentSubmitButton.spec.tsx
  src/app/payment/PaymentSubmitButton.tsx
Labels: important, integrations, ready to merge, reviewed, sydney

#632 fix(payment): INT-4598 handle vaulting Enable checkbox for Digital River
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
Labels: important, integrations, ready to merge, reviewed, sydney
