Repository bigcommerce/checkout-js, pull requests merged in 2022-09, with the labels that each got.

#994 fix(payment): INT-6115 Payment with hosted credit card
  packages/core/src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.spec.tsx
  packages/core/src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge, important

#978 fix(payment): INT-6404 AmazonPayV2: Prevent button flickering
  packages/core/src/app/customer/CheckoutButtonList.tsx
  packages/core/src/app/customer/customWalletButton/AmazonPayV2Button.spec.tsx
  packages/core/src/app/customer/customWalletButton/AmazonPayV2Button.tsx
  packages/core/src/app/customer/customWalletButton/index.ts
  packages/core/src/scss/components/checkout/checkoutRemote/_checkoutRemote.scss
Labels: integrations, sydney, reviewed, ready to merge

#988 fix(payment) INT-6328 Bluesnap open a new tab insted of using iframe to complete order
  packages/core/src/app/payment/paymentMethod/BlueSnapV2PaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge

#1001 chore(fix): Release INT-6328
  package-lock.json
  package.json
Labels: integrations, reviewable, sydney

#1013 feat(payment): INT-6482 | Worldpay - Increase coverage in WorldpayCreditCardPaymentMethod
  packages/core/src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.spec.tsx
  packages/core/src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.tsx
Labels: integrations, sydney, ready to merge, important

#1028 fix(payment): ADYEN-545 fixed adyen 3ds2 challenge window size
  package-lock.json
  package.json
  packages/core/src/scss/components/foundation/modal/_modal.scss
Labels: sydney

#1042 chore(payment): STRIPE-52 bump to 1.292.0 SDK version (#1616)
  package-lock.json
  package.json
Labels: integrations, reviewable, sydney
