Repository bigcommerce/checkout-js, pull requests merged in 2022-02, with the labels that each got.

#799 INT-5036 Enable to show oxxo ticket and boleto ticket link for StripeUPE
  src/app/order/OrderStatus.tsx
Labels: integrations, sydney, reviewed, ready to merge

#718 feat(payment): INT-4282 remove masterpass for Square
  src/app/payment/paymentMethod/SquarePaymentMethod.spec.tsx
  src/app/payment/paymentMethod/SquarePaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge

#801 feat(payment): INT-5467 Stripe UPE GooglePay
  src/app/customer/CheckoutButtonList.tsx
  src/app/payment/paymentMethod/GooglePayPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/GooglePayPaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethodId.ts
Labels: integrations, sydney, reviewed, ready to merge, on hold

#674 feat(order): INT-4776 Create a new field for the mandate reference ID
  package-lock.json
  package.json
  src/app/locale/translations/en.json
  src/app/order/OrderStatus.spec.tsx
  src/app/order/OrderStatus.tsx
  src/app/order/orders.mock.ts
Labels: integrations, reviewable, sydney

#808 feat(payment): INT-5384 Openpay: Add support to hosting their widget
  src/app/locale/translations/en.json
  src/app/payment/PaymentSubmitButton.spec.tsx
  src/app/payment/PaymentSubmitButton.tsx
  src/app/payment/paymentMethod/OpyPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/OpyPaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethod.spec.tsx
  src/app/payment/paymentMethod/PaymentMethod.tsx
  src/app/payment/paymentMethod/__snapshots__/OpyPaymentMethod.spec.tsx.snap
  src/scss/components/checkout/widget/_widget.scss
Labels: integrations, sydney, reviewed, ready to merge, important
