Repository bigcommerce/checkout-js, pull requests merged in 2022-05, with the labels that each got.

#869 chore(checkout): INT-5963 Bump Checkout SDK v1.244.0
  package-lock.json
  package.json
Labels: integrations, ready to merge, important

#862 feat(payment): INT-5904 Remove formatting for payment method when Mollie
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Labels: integrations, sydney, reviewed, ready to merge

#832 feat(payment): INT-5060 Stripe UPE Look and Feel - Get styles from store theme styles
  src/app/payment/paymentMethod/StripeUPEPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/StripeUPEPaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge

#836 feat(payment): INT-5754 Stripe UPE Added onError to initialize options
  src/app/payment/paymentMethod/StripeUPEPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/StripeUPEPaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge

#857 feat(payment): INT-5481 Worldpay component
  src/app/locale/translations/da.json
  src/app/locale/translations/de.json
  src/app/locale/translations/en.json
  src/app/locale/translations/es-419.json
  src/app/locale/translations/es-AR.json
  src/app/locale/translations/es-CL.json
  src/app/locale/translations/es-CO.json
  src/app/locale/translations/es-MX.json
  src/app/locale/translations/es-PE.json
  src/app/locale/translations/es.json
  src/app/locale/translations/fr.json
  src/app/locale/translations/it.json
  src/app/locale/translations/nl.json
  src/app/locale/translations/pt-BR.json
  src/app/locale/translations/pt.json
  src/app/locale/translations/sv.json
  src/app/payment/paymentMethod/PaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethodId.ts
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
  src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.tsx
  src/app/payment/paymentMethod/getPaymentMethodDisplayName.spec.tsx
  src/app/payment/paymentMethod/getPaymentMethodDisplayName.tsx
Labels: integrations, sydney, reviewed, ready to merge, important

#878 fix(checkout): INT-5126 [MPGS] Bump for add delay between calls for 3d
  package-lock.json
  package.json
Labels: integrations, reviewable, sydney, important
