Repository bigcommerce/checkout-js, pull requests merged in 2022-08, with the labels that each got.

#943 feat(payment): PAYPAL-1445 fixed storeCredit checkbox
  packages/core/src/app/payment/Payment.spec.tsx
  packages/core/src/app/payment/Payment.tsx
Labels: sydney

#937 feat(payment): STRIPE-82 Add code to show images on the list
  packages/core/src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Labels: integrations, sydney, reviewed, ready to merge

#915 feat(payment): INT-6115 Worldpay - remove unnecessary iframe
  packages/core/src/app/payment/Payment.tsx
  packages/core/src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge, important

#940 Fix(payment): STRIPE-53 Give more information on payment authentication with 3ds failure error message
  packages/core/src/app/locale/translations/en.json
  packages/core/src/app/payment/paymentMethod/StripePaymentMethod.spec.tsx
  packages/core/src/app/payment/paymentMethod/StripePaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge

#938 fix(payment): INT-5854 [Mollie] Klarna is not available if cart contains digital products
  package-lock.json
  package.json
  packages/core/src/app/locale/translations/da.json
  packages/core/src/app/locale/translations/de.json
  packages/core/src/app/locale/translations/en.json
  packages/core/src/app/locale/translations/es-419.json
  packages/core/src/app/locale/translations/es-AR.json
  packages/core/src/app/locale/translations/es-CL.json
  packages/core/src/app/locale/translations/es-CO.json
  packages/core/src/app/locale/translations/es-MX.json
  packages/core/src/app/locale/translations/es-PE.json
  packages/core/src/app/locale/translations/es.json
  packages/core/src/app/locale/translations/fr.json
  packages/core/src/app/locale/translations/it.json
  packages/core/src/app/locale/translations/nl.json
  packages/core/src/app/locale/translations/no.json
  packages/core/src/app/locale/translations/pt-BR.json
  packages/core/src/app/locale/translations/pt.json
  packages/core/src/app/locale/translations/sv.json
  packages/core/src/app/payment/paymentMethod/MolliePaymentMethod.spec.tsx
  packages/core/src/app/payment/paymentMethod/MolliePaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge

#981 chore(common): INT-0000 Update Checkout SDK
  package-lock.json
  package.json
Labels: integrations, sydney, reviewed, ready to merge

#969 fix(payment): INT-6392 [Mollie] Klarna shopper are able to place orders with digital items through klarna pay later and slice it when them are added via coupon
  package-lock.json
  package.json
  packages/core/src/app/payment/paymentMethod/MolliePaymentMethod.tsx
Labels: integrations, reviewable, sydney
