Repository bigcommerce/checkout-js, pull requests merged in 2022-01, with the labels that each got.

#772 fix(payment): ADYEN-296 Card fields validation
  package-lock.json
  package.json
  src/app/payment/paymentMethod/AdyenV2CardValidation.spec.tsx
  src/app/payment/paymentMethod/AdyenV2CardValidation.tsx
  src/app/payment/paymentMethod/AdyenV2PaymentMethod.spec.tsx
  src/app/payment/paymentMethod/AdyenV2PaymentMethod.tsx
Labels: sydney

#784 fix(payment): ADYEN-373 fix iDEAL payment
  package-lock.json
  package.json
Labels: sydney, ready to merge, bug, important

#781 feat(payment): INT-5331 Remove validation for Amazon Pay and all the time show an specific label
  src/app/billing/StaticBillingAddress.spec.tsx
  src/app/billing/StaticBillingAddress.tsx
Labels: integrations, sydney, reviewed, ready to merge

#782 feat(payment): PAYPAL-1257 replaced paypal credit logo
  src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
Labels: sydney

#786 feat(payment): BOLT-135 multi-field component
  package-lock.json
  package.json
  src/scss/components/bigcommerce/forms-ccFields/_forms-ccFields.scss
Labels: sydney

#758 fix(payment): INT-4674 GooglePay: reinitialize payment on payment select
  src/app/payment/paymentMethod/GooglePayPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/GooglePayPaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge

#770 feat(provider) INT-5031: Stripe UPE Payment Method
  src/app/payment/paymentMethod/PaymentMethod.tsx
  src/app/payment/paymentMethod/PaymentMethodId.ts
  src/app/payment/paymentMethod/PaymentMethodTitle.tsx
  src/app/payment/paymentMethod/StripeUPEPaymentMethod.spec.tsx
  src/app/payment/paymentMethod/StripeUPEPaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge

#791 chore(payment): INT-5402 Bump checkout-sdk
  package-lock.json
  package.json
Labels: integrations, reviewable, sydney, important

#798 feat(payment): INT-5460 Remove the word Payment from error title
  src/app/locale/translations/de.json
  src/app/locale/translations/en.json
  src/app/locale/translations/es-MX.json
  src/app/locale/translations/es.json
  src/app/locale/translations/fr.json
  src/app/locale/translations/it.json
  src/app/locale/translations/nl.json
  src/app/locale/translations/pt-BR.json
  src/app/locale/translations/pt.json
  src/app/locale/translations/sv.json
  src/app/payment/paymentMethod/DigitalRiverPaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge
