Repository bigcommerce/checkout-js, pull requests merged in 2022-10, with the labels that each got.

#1019 feat(payment): INT-6297 BNZ GooglePay
  packages/core/src/app/customer/CheckoutButtonList.tsx
  packages/core/src/app/payment/paymentMethod/GooglePayPaymentMethod.spec.tsx
  packages/core/src/app/payment/paymentMethod/GooglePayPaymentMethod.tsx
  packages/core/src/app/payment/paymentMethod/PaymentMethod.tsx
  packages/core/src/app/payment/paymentMethod/PaymentMethodId.ts
Labels: integrations, reviewable, sydney

#1017 feat(payment): STRIPE-25 create a custom guest form for Stripe link
  packages/apple-pay-integration/e2e/__har__/ApplePay-in-Customer-Step_453200396/recording.har
  packages/core/src/app/checkout/Checkout.spec.tsx
  packages/core/src/app/checkout/Checkout.tsx
  packages/core/src/app/customer/Customer.spec.tsx
  packages/core/src/app/customer/Customer.tsx
  packages/core/src/app/customer/StripeGuestForm.spec.tsx
  packages/core/src/app/customer/StripeGuestForm.tsx
  packages/core/src/app/customer/__snapshots__/StripeGuestForm.spec.tsx.snap
  packages/core/src/app/locale/translations/en.json
  packages/core/src/app/payment/Payment.spec.tsx
  packages/core/src/app/payment/Payment.tsx
  packages/core/src/app/payment/paymentMethod/HostedPaymentMethod.spec.tsx
  packages/core/src/scss/components/checkout/customer/_customer.scss
Labels: integrations, sydney, reviewed, ready to merge

#1018 feat(payment): STRIPE-52 Auto-Select Address and mount shipping component for Stripe Link
  packages/apple-pay-integration/e2e/__har__/ApplePay-in-Customer-Step_453200396/recording.har
  packages/apple-pay-integration/e2e/__har__/ApplePay-in-Payment-Step_2100856370/recording.har
  packages/core/src/app/billing/Billing.spec.tsx
  packages/core/src/app/checkout/Checkout.tsx
  packages/core/src/app/shipping/RemoteShippingAddress.spec.tsx
  packages/core/src/app/shipping/Shipping.spec.tsx
  packages/core/src/app/shipping/Shipping.tsx
  packages/core/src/app/shipping/StaticAddressEditable.spec.tsx
  packages/core/src/app/shipping/stripeUPE/StripeShipping.spec.tsx
  packages/core/src/app/shipping/stripeUPE/StripeShipping.tsx
  packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.spec.tsx
  packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.tsx
  packages/core/src/app/shipping/stripeUPE/StripeShippingAddressDisplay.tsx
  packages/core/src/app/shipping/stripeUPE/StripeShippingForm.spec.tsx
  packages/core/src/app/shipping/stripeUPE/StripeShippingForm.tsx
  packages/core/src/app/shipping/stripeUPE/StripeStateMapper.spec.ts
  packages/core/src/app/shipping/stripeUPE/StripeStateMapper.ts
  packages/core/src/app/shipping/stripeUPE/StripeupeShippingAddress.spec.tsx
  packages/core/src/app/shipping/stripeUPE/__snapshots__/StripeupeShippingAddress.spec.tsx.snap
  packages/hosted-credit-card-integration/e2e/__har__/sample-Bigpay-Test-Payment-Provider_3530407662/recording.har
Labels: integrations, sydney, reviewed, ready to merge

#1047 fix(payment): INT-6478 SquareV2 - Fail Gracefully when payment provider unavailable
  packages/core/src/app/payment/paymentMethod/SquarePaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge

#1068 fix(payment): INT-6789 Worldpay Support payment without hosted form
  packages/core/src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.spec.tsx
  packages/core/src/app/payment/paymentMethod/WorldpayCreditCardPaymentMethod.tsx
Labels: integrations, sydney, ready to merge, important

#1070 feat(payment): INT-6637 Sezzle change displayed text
  packages/core/src/app/locale/translations/en.json
Labels: integrations, sydney, ready to merge

#1057 fix(payment): INT-6720 prevent calls on undefined error body
  packages/core/src/app/payment/Payment.spec.tsx
  packages/core/src/app/payment/Payment.tsx
Labels: integrations, sydney, reviewed, ready to merge, important

#1081 chore(payment): INT-6772 Bump checkout-sdk to 1.299.1
  package-lock.json
  package.json
Labels: integrations, sydney, reviewed, ready to merge
