Repository bigcommerce/checkout-js, pull requests merged in 2022-12, with the labels that each got.

#1122 fix(payment): STRIPE-0000 bump checkout-sdk-js v1.309.6
  package-lock.json
  package.json
Labels: integrations, reviewable, sydney, ready to merge

#1110 fix(payment): INT-6928 [Mollie] No Ability To Use A Different Card To Pay
  packages/core/src/app/payment/paymentMethod/HostedWidgetPaymentMethod.spec.tsx
  packages/core/src/app/payment/paymentMethod/HostedWidgetPaymentMethod.tsx
  packages/hosted-widget-integration/src/HostedWidgetPaymentComponent.spec.tsx
  packages/hosted-widget-integration/src/HostedWidgetPaymentComponent.tsx
Labels: integrations, reviewable, sydney, important

#1058 feat(payment): INT-6715 SquareV2: Add payment method component
  packages/core/src/app/payment/paymentMethod/PaymentMethodV2.spec.tsx
  packages/core/src/app/payment/paymentMethod/PaymentMethodV2.tsx
  packages/squarev2-integration/.eslintrc.json
  packages/squarev2-integration/README.md
  packages/squarev2-integration/e2e/__har__/SquareV2-in-Payment-Step_656806659/recording.har
  packages/squarev2-integration/e2e/squarev2.spec.ts
  packages/squarev2-integration/e2e/support/square.mock.js
  packages/squarev2-integration/jest.config.js
  packages/squarev2-integration/project.json
  packages/squarev2-integration/src/SquareV2PaymentMethod.spec.tsx
  packages/squarev2-integration/src/SquareV2PaymentMethod.tsx
  packages/squarev2-integration/src/__snapshots__/SquareV2PaymentMethod.spec.tsx.snap
  packages/squarev2-integration/src/index.ts
  packages/squarev2-integration/src/mocks/squarev2-method.mock.ts
  packages/squarev2-integration/tsconfig.json
  packages/squarev2-integration/tsconfig.lib.json
  packages/squarev2-integration/tsconfig.spec.json
  packages/ui/src/index.ts
  packages/ui/src/utils/dom/getAppliedStyles.spec.ts
  packages/ui/src/utils/dom/getAppliedStyles.ts
  packages/ui/src/utils/dom/index.ts
  tsconfig.base.json
  workspace.json
Labels: integrations, sydney, reviewed, ready to merge, important
