Repository bigcommerce/checkout-js, pull requests merged in 2023-08, with the labels that each got.

#1408 feat(payment): PAYPAL-1545 bump checkout-sdk-js version
  package-lock.json
  package.json
Labels: sydney

#1380 feat(payment): PAYPAL-1545 added translation for PaypalCommerce RatePay payment component
  packages/locale/src/translations/en.json
Labels: sydney

#1437 Update translations
  packages/locale/src/translations/da.json
  packages/locale/src/translations/de.json
  packages/locale/src/translations/es-419.json
  packages/locale/src/translations/es-AR.json
  packages/locale/src/translations/es-CL.json
  packages/locale/src/translations/es-CO.json
  packages/locale/src/translations/es-LA.json
  packages/locale/src/translations/es-MX.json
  packages/locale/src/translations/es-PE.json
  packages/locale/src/translations/es.json
  packages/locale/src/translations/fr.json
  packages/locale/src/translations/it.json
  packages/locale/src/translations/nl.json
  packages/locale/src/translations/no.json
  packages/locale/src/translations/pl.json
  packages/locale/src/translations/pt-BR.json
  packages/locale/src/translations/pt.json
  packages/locale/src/translations/sv.json
Labels: update-translations-svc

#1473 chore(payment): INT-5659 Bump checkout-sdk from `1.436.0` to `1.437.0`
  package-lock.json
  package.json
Labels: integrations, reviewable, sydney
