Repository bigcommerce/checkout-js, pull requests merged in 2023-02, with the labels that each got.

#1182 chore(payment): STRIPE-0 checkout-sdk bump version 1.355.0
  package-lock.json
  package.json
Labels: integrations, sydney, reviewed, ready to merge

#1177 feat(payment): STRIPE-280 using addressFormSkeleton instead spinner for stripeLink components
  packages/core/src/app/customer/StripeGuestForm.tsx
  packages/core/src/app/customer/__snapshots__/StripeGuestForm.spec.tsx.snap
  packages/core/src/app/shipping/stripeUPE/StripeShipping.tsx
Labels: integrations, sydney, reviewed, ready to merge

#1206 fix(payment): INT-7522 SquareV2: Disable submit only if payment data is required
  packages/squarev2-integration/src/SquareV2PaymentMethod.spec.tsx
  packages/squarev2-integration/src/SquareV2PaymentMethod.tsx
Labels: integrations, sydney, reviewed, ready to merge, important

#1069 test(payment): INT-6517 Increase BluesnapV2 payment method coverage
  packages/core/src/app/payment/paymentMethod/BlueSnapV2PaymentMethod.spec.tsx
  packages/core/src/app/payment/paymentMethod/BlueSnapV2PaymentMethod.tsx
Labels: integrations, sydney, reviewed

#1100 feat(payment): STRIPE-200 add phone number for stripe link
  packages/core/src/app/payment/paymentMethod/StripeUPEPaymentMethod.tsx
  packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.spec.tsx
  packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.tsx
Labels: integrations, sydney, reviewed, ready to merge, important

#1200 fix(shipping): STRIPE-202 Split name input into First and Last name
  package-lock.json
  package.json
  packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.spec.tsx
  packages/core/src/app/shipping/stripeUPE/StripeShippingAddress.tsx
Labels: integrations, sydney, reviewed, ready to merge, important
