Repository bigcommerce/checkout-js, pull requests merged in 2023-01, with the labels that each got.

#1109 fix(payment): STRIPE-175 remove extra payment call and extra code on core
  packages/core/src/app/customer/Customer.spec.tsx
  packages/core/src/app/customer/Customer.tsx
  packages/core/src/app/shipping/Shipping.spec.tsx
  packages/core/src/app/shipping/Shipping.tsx
Labels: integrations, sydney, reviewed, ready to merge

#1116 fix(payment): STRIPE-269 exclude wallets from the custom customer step status for stripeLink
  packages/core/src/app/checkout/getCheckoutStepStatuses.spec.ts
  packages/core/src/app/checkout/getCheckoutStepStatuses.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1130 refactor(payment): INT-6964 Sunset Amazon Pay V1
  packages/core/src/app/billing/StaticBillingAddress.spec.tsx
  packages/core/src/app/billing/StaticBillingAddress.tsx
  packages/core/src/app/checkout/checkouts.mock.ts
  packages/core/src/app/checkout/getCheckoutStepStatuses.spec.ts
  packages/core/src/app/checkout/getCheckoutStepStatuses.ts
  packages/core/src/app/customer/CheckoutButtonList.spec.tsx
  packages/core/src/app/customer/CheckoutButtonList.tsx
  packages/core/src/app/customer/__snapshots__/CheckoutButtonList.spec.tsx.snap
  packages/core/src/app/customer/canSignOut.spec.ts
  packages/core/src/app/customer/canSignOut.ts
  packages/core/src/app/embeddedCheckout/createEmbeddedCheckoutSupport.ts
  packages/core/src/app/locale/translations/da.json
  packages/core/src/app/locale/translations/de.json
  packages/core/src/app/locale/translations/en.json
  packages/core/src/app/locale/translations/es-419.json
  packages/core/src/app/locale/translations/es-AR.json
  packages/core/src/app/locale/translations/es-CL.json
  packages/core/src/app/locale/translations/es-CO.json
  packages/core/src/app/locale/translations/es-MX.json
  packages/core/src/app/locale/translations/es-PE.json
  packages/core/src/app/locale/translations/es.json
  packages/core/src/app/locale/translations/fr.json
  packages/core/src/app/locale/translations/it.json
  packages/core/src/app/locale/translations/nl.json
  packages/core/src/app/locale/translations/no.json
  packages/core/src/app/locale/translations/pt-BR.json
  packages/core/src/app/locale/translations/pt.json
  packages/core/src/app/locale/translations/sv.json
  packages/core/src/app/payment/Payment.tsx
  packages/core/src/app/payment/PaymentSubmitButton.spec.tsx
  packages/core/src/app/payment/PaymentSubmitButton.tsx
  packages/core/src/app/payment/paymentMethod/AmazonPaymentMethod.spec.tsx
  packages/core/src/app/payment/paymentMethod/AmazonPaymentMethod.tsx
  packages/core/src/app/payment/paymentMethod/PaymentMethod.tsx
  packages/core/src/app/payment/paymentMethod/PaymentMethodId.ts
  packages/core/src/app/payment/paymentMethod/PaymentMethodTitle.spec.tsx
  packages/core/src/app/payment/paymentMethod/PaymentMethodTitle.tsx
  packages/core/src/app/payment/paymentMethod/getPaymentMethodName.spec.ts
  packages/core/src/app/payment/paymentMethod/getPaymentMethodName.ts
  packages/core/src/app/shipping/RemoteShippingAddress.spec.tsx
  packages/core/src/app/shipping/RemoteShippingAddress.tsx
  packages/core/src/app/shipping/ShippingAddress.spec.tsx
  packages/core/src/app/shipping/ShippingAddress.tsx
  packages/core/src/app/shipping/ShippingForm.spec.tsx
  packages/core/src/app/shipping/SingleShippingForm.spec.tsx
  packages/core/src/app/shipping/SingleShippingForm.tsx
  packages/core/src/app/shipping/getShippingMethodId.ts
  packages/core/src/app/shipping/mapToShippingProps.spec.ts
  packages/core/src/app/shipping/shippingOption/ShippingOptionsForm.spec.tsx
  packages/core/src/app/shipping/stripeUPE/StripeShippingForm.spec.tsx
  packages/core/src/scss/components/checkout/widget/_widget.scss
  packages/locale/src/en.json
  packages/payment-integration-api/src/getPaymentMethodName.ts
  packages/test-utils/src/checkout.mock.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1165 chore(payment): INT-7103 Bump checkout-sdk from 1.324.1 to 1.324.2
  package-lock.json
  package.json
Labels: integrations, reviewable, sydney, important
